version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      spring.datasource.username: "postgres"
      spring.datasource.password: "docker"
      spring.datasource.url: "jdbc:postgresql://db:5432/postgres"
  db:
    image: postgres:10
    ports:
      - "8001:5432"
    environment:
      POSTGRES_PASSWORD: docker
